environment:
  matrix:
    - MINICONDA: C:\Miniconda36-x64

init:
  - cmd: set PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - cmd: echo %path%

install:
  - "conda config --set always_yes yes"
  - "conda info -a"
  - "conda env create -f environment.yml"
  - "activate holoviews"
  - "python setup.py develop"

build: false

before_test:
  - cmd: for /f %%i in ('python -c "import matplotlib; print(matplotlib.matplotlib_fname())"') do set matplotlibrc=%%i
  - cmd: 'echo backend : Agg > %matplotlibrc%'

test_script:
  - "flake8 --ignore=E,W,F999,F405 holoviews"
  - "nosetests --with-doctest --with-coverage --cover-package=holoviews"
