environment:
  matrix:
    - PY: "2.7"
      CONDA: "C:\\Miniconda-x64"
    - PY: "3.6"
      CONDA: "C:\\Miniconda36-x64"

matrix:
  allow_failures:
    - PY: "2.7"
    - PY: "3.6"

init:
  - cmd: set PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;%PATH%
  - cmd: echo %path%

install:
  - "conda config --set always_yes yes"
  - "conda update -q conda"
  - "conda info -a"
  - "conda create -n holoviews python=%PY%"
  - "conda env update -n holoviews -f environment.yml"
  - "activate holoviews"
  - "python setup.py develop"

build: false

before_test:
  - cmd: for /f %%i in ('python -c "import matplotlib; print(matplotlib.matplotlib_fname())"') do set matplotlibrc=%%i
  - cmd: 'echo backend : Agg > %matplotlibrc%'

test_script:
  - "flake8 --ignore=E,W,F999,F405 holoviews"
  - "nosetests --with-doctest --with-coverage --cover-package=holoviews"
