name: holoviews

dependencies:
  - numpy<1.16.0
  - notebook
  - matplotlib
  - pandas=0.24.0
  - scipy
  - xarray=0.11.0
  - networkx
  - ipython=5.4.1
  - jsonschema=2.6.0
  - cyordereddict
  - nbconvert=5.3.1
  - selenium
  - pyviz::param=1.8.1
  - pyviz::pyviz_comms=0.7.0
  - pyviz::datashader
  - conda-forge::netcdf4=1.3.1
  - conda-forge::ffmpeg
  - conda-forge::flexx=0.4.1
  - conda-forge::plotly=3.4
  - conda-forge::bokeh=1.0.4
  - conda-forge::pillow
  # Testing requirements
  - flake8
  - nose
  - path.py
  - conda-forge::deepdiff
  - conda-forge::awscli
  - conda-forge::coveralls
