name: holoviews

channels:
  - conda-forge

dependencies:
  - numpy
  - notebook
  - matplotlib
  - pandas=0.24.0
  - scipy
  - xarray=0.11.0
  - networkx
  - ipython=5.4.1
  - jsonschema=2.6.0
  - cyordereddict
  - nbconvert=5.3.1
  - selenium
  - netcdf4=1.3.1
  - ffmpeg
  - flexx=0.4.1
  - plotly=3.4
  - bokeh=1.0.4
  - pillow
  - pyviz::param=1.8.1
  - pyviz::pyviz_comms=0.7.0
  - pyviz::datashader
  # Testing requirements
  - flake8
  - nose
  - path.py
  - deepdiff
  - awscli
  - coveralls
